task0. Creating PointCloud from depth and annotation images
true-real-michael/SLAM-spbu-ss22 pull request #1
Opened 2022-07-08 11:20 UTC by true-real-michael

2022-07-08 17:25 UTC, DmiitriyJarosh requested changes

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/.idea/.gitignore
> +# Default ignored files
давайте почитаете про то что такое .gitignore и как им пользоваться. Папку `.idea` коммитить не стоит, она содержит мета информацию ide и не обязательна для открытия проекта и его запуска. Соответсвенно нужно добавить эту папку в игнор и убрать из репо

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/main.ipynb
> +{
Python ноутбуки удобны для быстрого воспроизведения эксперимента, однако плохи, когда код нужно переиспользовать или рецензировать. Предлагаю в дальнейшем в виде ноутбуков заливать только эксперименты, которые хочется именно визуализировать как то, а весь остальной код держать в обычных py файлах

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/main.ipynb
> +    "K_ = np.matrix([[481.20, 0, 319.50, 0],\n",
какой смысл заложен в названии переменной? Давайте называть так, чтобы человек который не знает конкретную формулу наизусть, все равно мог понять о чем речь, например что это матрица каких параметров камеры

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/main.ipynb
> +    "    z = d / 5000\n",
5000 - magic number, такие вещи нужно обьявлять в виде констант с понятным именем

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/main.ipynb
> +    "    xyz1 = z * K_inv @ np.array([u, v, 1, 1 / z]).transpose()\n",
xyz1 - нэйминг поправить

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/main.ipynb
> +    "              for u in range(depths_img.size[0]) for v in range(depths_img.size[1])]\n",
подход с циклами работать будет, но очень медленно, давайте почитаем про то как numpy позволяет ускорить вычисления используя матричные операции - например можно умножать всю матрицу на число просто написав M * 3 и тд. Давайте перепишем это место полностью без циклов

2022-07-08 17:25 UTC, DmiitriyJarosh commented on task0/main.ipynb
> +    "    return np.array(points), np.array(colors) / 256\n"
а зачем тут цвета? каждый метод должен выполнять одну задачу, а не несколько параллельно

2022-07-09 12:05 UTC, true-real-michael commented on task0/main.ipynb
> +    "K_ = np.matrix([[481.20, 0, 319.50, 0],\n",
Я сначала поменял `K` на `intrinsic_matrix`, но потом удалил и вместо нее добавил `fx`, `fy`, `cx`, `cy`

2022-07-09 17:45 UTC, DmiitriyJarosh commented on task0/main.py
> +colors_image = Image.open('data/annot.png')
почитайте про конструкцию `if __name__ == "__main__":`

2022-07-09 17:45 UTC, DmiitriyJarosh commented on task0/main.py
> +u_coordinates = uvd_points_vector[:, 0]
а зачем были эти манипуляции с вектором из координат и глубины? если снова все достали, решейп можно было ведь сразу сделать наверно?

2022-07-12 03:30 UTC, DmiitriyJarosh approved these changes

2022-07-12 03:30 UTC, DmiitriyJarosh commented on task0/main.py
> +    visualize_pointcloud(get_points_vector('data/depth.png'),
codestyle - такие отступы выглядят странно (ожидаю каждый аргумент с новой строки, раз уж начали переносить), в PyCharm можно например нажать Ctrl+Alt+L вроде и оно само отформатирует файл

2022-07-12 07:49 UTC, true-real-michael commented on task0/main.py
> +    visualize_pointcloud(get_points_vector('data/depth.png'),
а это вроде соответствует pep8
![image](https://user-images.githubusercontent.com/64229743/178437132-1372944c-96dd-4d3d-8ffa-785b06fed05e.png)

2022-07-14 11:19 UTC, merged